Test Case verifyMacBookIsAddedToProductComparison is Added
PivotITAcademy/3rd-Septmeber-Automation-Framework pull request #13
Opened 2023-01-29 02:46 UTC by Daman1231

2023-01-29 22:22 UTC, PivotITAcademy requested changes
Plz do the necessary changes

2023-01-29 22:22 UTC, PivotITAcademy commented on src/main/java/com/naveenautomation/Pages/DesktopPage.java
> +	private static final String PAGE_URL = "/category&path=20";
we can't have &path=20 in page URL

2023-01-29 22:22 UTC, PivotITAcademy commented on src/test/java/com/naveenautomation/tests/DesktopTest.java
> +	AccountLoginPage accountLoginPage;
Add access modifiers

2023-01-30 18:27 UTC, Daman1231 commented on src/main/java/com/naveenautomation/Pages/DesktopPage.java
> +	private static final String PAGE_URL = "/category&path=20";
Removed

2023-01-30 18:27 UTC, Daman1231 commented on src/test/java/com/naveenautomation/tests/DesktopTest.java
> +	AccountLoginPage accountLoginPage;
Access modifier added

2023-02-01 18:41 UTC, PivotITAcademy approved these changes
LGTM

2023-02-01 19:55 UTC, merged